### PR TITLE
Story 13

### PR DESCRIPTION
**Pull request by emcooper**
**Finishes story 13**
- Adds Item_Order models, and tables
- User can view individual Order show page

### CODE REVIEW

**Comment by JoelLindow** [comment]
Ellen. This looks really good. I've seen some similar code in the past and it was really bad. This is by far the best commit so far.

**Comment by JoelLindow** [comment]
Ellen. Thank you for this contribution.

I feel like when I look at the show page that I'm seeing a lot of logic that could be "pushed down the stack" a little further. Also, while "we're" at it , "let's" dry up that controller a little bit.

Good try. "We'll" get it on the next story.

**Comment by emcooper** [comment]
Thanks for the "constructive" feedback, Joel.

**Comment by JoelLindow** [comment]
¯\_(ツ)_/¯

**Pull request merged**
